### ISSUE TITLE
Missing datasets folder from groundingdino

### ISSUE THREAD

**Issue by YukunLi99** [JarintotionDin/ZiRaGroundingDINO#1]
cannot import name 'DetrDatasetMapper' from 'groundingdino.datasets' (unknown location)

**Comment by JarintotionDin** [comment]
DetrDatasetMapper has been added.

**Comment by JarintotionDin** [comment]
> DetrDatasetMapper has been added.

if there is any bug, please tell me.

**Comment by YukunLi99** [comment]
Sorry for taking so long to reply to the message, here's something that confuses me:
1. I have carefully read the dataset.py file in `groundingdino/config/configs/common/data/odinw`, and I noticed a slight difference compared to the ODinW-13 dataset used by GLIP and GroundingDINO. For example, GLIP uses "AerialMaritimeDrone large," while this repository uses "AerialMaritimeDrone tiled." Additionally, GLIP uses "North American Mushrooms.v1-416x416.coco," whereas this repository uses "North American Mushrooms.v2-416x416augmented.coco," and so on. Please refer to [this](https://github.com/microsoft/GLIP/tree/main/configs/odinw_13) for further information.
2. I am unsure whether the evaluation metrics for ODinW-13 should be applied to the test dataset or the validation dataset. However, in GLIP, the evaluation is actually performed on the validation dataset. Please refer to [this](https://github.com/microsoft/GLIP/blob/main/configs/odinw_13/AerialMaritimeDrone_large.yaml#L93 ) for further information.
3. I am confused about the Testing Protocols, and I am unsure whether the evaluation is conducted based on class incremental learning or task incremental learning without IDs. Referring to `train_odinw13_zero_shot.sh`, it seems to be more aligned with the latter, as during the inference process, the script does not input the names of all the previously seen classes. However, the paper describes that "This means that the dataset ID will not be provided, and the model should predict **all learned classes** across all datasets and domains during testing.”
4. The config file uses the training set as the evaluation dataset. Please refer to [NorthAmericaMushrooms.py](https://github.com/JarintotionDin/ZiRaGroundingDINO/blob/main/groundingdino/config/configs/common/data/odinw/NorthAmericaMushrooms.py#L26).

**Comment by JarintotionDin** [comment]
1.This repository uses "AerialMaritimeDrone tiled"，because there are some bugs that i can't fixed when reading images in "AerialMaritimeDrone large". The same reason is for using "North American Mushrooms.v2-416x416augmented.coco". In the paper, we compare all methods using the same datasets.
2. We use test dataset, and we did not compared our method with GLIP. If you want to use validation dataset, just change the config file as you want.
3. When training, the model will record all learned class names. When testing, all learned names will be add to the input. Please  refer [this](https://github.com/JarintotionDin/ZiRaGroundingDINO/blob/main/groundingdino/models/GroundingDINO/groundingdino_dual_zero_rep_branch.py)

     ``` if (self.use_add_names and (not self.training)) or (self.use_learned_names and self.training):
            non_overlap_classes = [class_name for class_name in \
                self.learned_classes if (class_name not in names_list[0])]
            if self.training and (len(non_overlap_classes) >= self.num_select_prompt):
                    non_overlap_classes = random.sample(non_overlap_classes, self.num_select_prompt)    
            for idx, (caption, names) in enumerate(zip(captions, names_list)):
                names_list[idx] = names + non_overlap_classes
                captions[idx] = caption + ".".join(non_overlap_classes)
                if not captions[idx].endswith("."): captions[idx] = captions[idx] + "." 

4. This is a mistake, we will fixed it, and updated our results in the paper.

**Comment by JarintotionDin** [comment]
We just remembered that because the testing set of North American Mushrooms has too few images, we instead used North American "Mushrooms.v1-416x416.coco/train" as the training set, "North American Mushrooms.v2-416x416augmented.coco/train"" as the test set.  These two training set are quiet different, so we think it is reasonable. There is no mistake.

**Comment by YukunLi99** [comment]
I noticed that by default, the "**use_add_names**" is set to False, which means the subsequent content is not executed.
```
if (self.use_add_names and (not self.training)) or (self.use_learned_names and self.training):
            non_overlap_classes = [class_name for class_name in \
                self.learned_classes if (class_name not in names_list[0])]
            if self.training and (len(non_overlap_classes) >= self.num_select_prompt):
                    non_overlap_classes = random.sample(non_overlap_classes, self.num_select_prompt)    
            for idx, (caption, names) in enumerate(zip(captions, names_list)):
                names_list[idx] = names + non_overlap_classes
                captions[idx] = caption + ".".join(non_overlap_classes)
                if not captions[idx].endswith("."): captions[idx] = captions[idx] + "."
```
```
model = GroundingDINO(
        backbone,
        transformer,
        num_queries=args.num_queries,
        aux_loss=args.aux_loss,
        iter_update=True,
        query_dim=4,
        num_feature_levels=args.num_feature_levels,
        nheads=args.nheads,
        dec_pred_bbox_embed_share=dec_pred_bbox_embed_share,
        two_stage_type=args.two_stage_type,
        two_stage_bbox_embed_share=args.two_stage_bbox_embed_share,
        two_stage_class_embed_share=args.two_stage_class_embed_share,
        num_patterns=args.num_patterns,
        dn_number=0,
        dn_box_noise_scale=args.dn_box_noise_scale,
        dn_label_noise_ratio=args.dn_label_noise_ratio,
        dn_labelbook_size=dn_labelbook_size,
        text_encoder_type=args.text_encoder_type,
        sub_sentence_present=sub_sentence_present,
        max_text_len=args.max_text_len,
        criterion=criterion,
        freeze_all=args.freeze_all,
        select_box_nums_for_evaluation=args.select_box_nums_for_evaluation,
        use_cet=args.use_cet,
        use_prompt_memory=args.use_prompt_memory,
        use_zero_inter_loss=args.use_zero_inter_loss,
        loss_adapter_weight=args.loss_adapter_weight,
        num_experts=args.num_experts,
        topk=args.num_topk_experts,
        cet_middle_dim=args.cet_middle_dim,
        use_bert_tuning=args.use_bert_tuning,
        use_cls_linear=args.use_cls_linear,
        use_prompt_tuning=args.use_prompt_tuning,
        use_prompt_memory_output=args.use_prompt_memory_output,
        cet_type=args.cet_type,
        use_project_tuning=use_project_tuning,
        use_learned_names=use_learned_names,
        use_project_adapter=use_project_adapter,
        use_zero_inter_loss_for_conv=use_zero_inter_loss_for_conv,
    )
 ```
**use_add_names** is not passed here; instead, it defaults to False.
```
class GroundingDINO(nn.Module):
    def __init__(
        self,
        ...
        use_add_names=False,
        ...
        use_learned_names=False,
    ):
```

**Comment by YukunLi99** [comment]
Does "**train_odinw13_zira.sh**" correspond to the training script for ZiRa?

**Comment by YukunLi99** [comment]
In fact, the default value of self.learned_classes is an empty list, indicating that the evaluation is based on TIL (Task Incremental Learning) rather than CIL (Class Incremental Learning). Please refer to [this](https://github.com/JarintotionDin/ZiRaGroundingDINO/blob/main/groundingdino/models/GroundingDINO/groundingdino_dual_zero_rep_branch.py#L231).
```
# learned classes
self.learned_classes = []
```

**Comment by JarintotionDin** [comment]
Thanks, all the bug has been fixed.
