### ISSUE TITLE
What is the mechmind_easy dataset

### ISSUE THREAD

**Issue by witnessai** [JarintotionDin/ZiRaGroundingDINO#2]
The command 'sh train_odinw13_zira.sh' reports an error: FileNotFoundError: [Errno 2] No such file or directory: 'datasets/mechmind_easy/mechmind_easy.json'. What is the mechmind_easy dataset?

**Comment by JarintotionDin** [comment]
Could you provide me a detail error track, so i can fixed it? The mechmind_easy dataset is a custom dataset used for visualization and validation, and it is not included in ODinW 13 datasets. I remove it in the current commit.

**Comment by witnessai** [comment]
This issue can be resolved by commenting out the content after line 302 in the file ZiRaGroundingDINO/groundingdino/datasets/builtin.py, thx
